POST http://localhost:3000/addUser HTTP/1.1
Content-Type: application/json

{
    "name": "TestUser2",
    "email": "testuser2@example.com",
    "password": "2222"
}

### 

GET http://localhost:3000/getAllUsers HTTP/1.1

###

DELETE http://localhost:3000/deleteUser/1 HTTP/1.1

###

POST http://localhost:3000/addHistoryEntry HTTP/1.1
Content-Type: application/json

{
    "userId": 4,
    "themaId": 1,
    "frage": "Deine Frage hier",
    "antwort": "Die Antwort hier",
    "timestamp": "2023-10-26 12:00:00"
}

###

GET http://localhost:3000/getUserHistory/4 HTTP/1.1
