### Generiert Frage und Antwort
POST http://localhost:3000/generate HTTP/1.1
Content-Type: application/json

{
    "topic": "Sports",
    "nbQuestions": "3"
}

### Generiert Frage und Antwort mit topic als param
POST http://localhost:3000/generate/Hockey HTTP/1.1
Content-Type: application/json

{
    "nbQuestions": "3"
}


### Konfiguriert Einstellungen 
POST http://localhost:3000/setConfiguration HTTP/1.1
Content-Type: application/json

{
    "language": "de",
    "languageLevel": "normal",
    "difficulty": "easy",
    "temperature": 0.9
}

### 
POST http://localhost:3000/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="pdfFile"; filename="Foliensatz.pdf"
Content-Type: application/pdf

< ./Foliensatz.pdf
--boundary--

###

POST http://localhost:3000/generateFromDocs HTTP/1.1
Content-Type: application/json

{
    "nbQuestions": "3"

}