### Generiert Frage und Antwort
POST http://localhost:3000/generate HTTP/1.1
Content-Type: application/json

{
    "topic": "Hockey",
    "nbQuestions": "3"
}

### Generiert Frage und Antwort mit topic als param
POST http://localhost:3000/generate/Hockey HTTP/1.1
Content-Type: application/json

{
    "nbQuestions": "3"
}


### Konfiguriert Einstellungen 
POST http://localhost:3000/setConfiguration HTTP/1.1
Content-Type: application/json

{
    "language": "en",
    "languageLevel": "C2",
    "difficulty": "hard",
    "temperature": 0.9
}